'use client';

import * as React from 'react';

/**
 * Embeds a Razorpay Payment Button exactly as generated by the Razorpay
 * Dashboard (Payment Pages -> Payment Button) — see content/donation-button.ts
 * for the button ID and the Razorpay-provided embed this is built from:
 *
 *   <form><script src="https://checkout.razorpay.com/v1/payment-button.js"
 *     data-payment_button_id="pl_xxx" async></script></form>
 *
 * Any amount-selection UI (presets, custom amount) is configured on the
 * button itself in the Dashboard and rendered inside Razorpay's own hosted
 * checkout when the button is clicked — nothing about the amount is
 * prefilled or simulated here.
 *
 * Razorpay's payment-button.js script replaces its own <script> tag with a
 * real <button> element as soon as it loads. The script MUST sit inside a
 * <form> element — confirmed by testing: rendering it inside a plain <div>
 * makes Razorpay's own script alert "Payment Button is not added. Add
 * Button script inside 'form' tag." and refuse to render anything.
 */
export function RazorpayDonationButton({ buttonId }: { buttonId: string }) {
  const containerRef = React.useRef<HTMLFormElement>(null);

  React.useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    container.innerHTML = '';
    const script = document.createElement('script');
    script.src = 'https://checkout.razorpay.com/v1/payment-button.js';
    script.async = true;
    script.dataset.payment_button_id = buttonId;
    container.appendChild(script);

    return () => {
      container.innerHTML = '';
    };
  }, [buttonId]);

  return <form ref={containerRef} />;
}
